--
-- PostgreSQL database dump
--

-- Dumped from database version 11.8 (Ubuntu 11.8-1.pgdg19.10+1)
-- Dumped by pg_dump version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)

--
-- Name: timescaledb; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "timescaledb" WITH SCHEMA "public";


--
-- Name: EXTENSION "timescaledb"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "timescaledb" IS 'Enables scalable inserts and complex queries for time-series data';


--
-- Name: traccar; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA "traccar";


--
-- Name: databasechangelog; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."databasechangelog" (
    "id" character varying(255) NOT NULL,
    "author" character varying(255) NOT NULL,
    "filename" character varying(255) NOT NULL,
    "dateexecuted" timestamp without time zone NOT NULL,
    "orderexecuted" integer NOT NULL,
    "exectype" character varying(10) NOT NULL,
    "md5sum" character varying(35),
    "description" character varying(255),
    "comments" character varying(255),
    "tag" character varying(255),
    "liquibase" character varying(20),
    "contexts" character varying(255),
    "labels" character varying(255),
    "deployment_id" character varying(10)
);


--
-- Name: databasechangeloglock; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."databasechangeloglock" (
    "id" integer NOT NULL,
    "locked" boolean NOT NULL,
    "lockgranted" timestamp without time zone,
    "lockedby" character varying(255)
);


--
-- Name: tc_attributes; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_attributes" (
    "id" integer NOT NULL,
    "description" character varying(4000) NOT NULL,
    "type" character varying(128) NOT NULL,
    "attribute" character varying(128) NOT NULL,
    "expression" character varying(4000) NOT NULL
);


--
-- Name: tc_attributes_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_attributes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_attributes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_calendars; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_calendars" (
    "id" integer NOT NULL,
    "name" character varying(128) NOT NULL,
    "data" "bytea" NOT NULL,
    "attributes" character varying(4000) NOT NULL
);


--
-- Name: tc_calendars_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_calendars" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_calendars_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_commands; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_commands" (
    "id" integer NOT NULL,
    "description" character varying(4000) NOT NULL,
    "type" character varying(128) NOT NULL,
    "textchannel" boolean DEFAULT false NOT NULL,
    "attributes" character varying(4000) NOT NULL
);


--
-- Name: tc_commands_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_commands" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_commands_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_device_attribute; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_device_attribute" (
    "deviceid" integer NOT NULL,
    "attributeid" integer NOT NULL
);


--
-- Name: tc_device_command; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_device_command" (
    "deviceid" integer NOT NULL,
    "commandid" integer NOT NULL
);


--
-- Name: tc_device_driver; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_device_driver" (
    "deviceid" integer NOT NULL,
    "driverid" integer NOT NULL
);


--
-- Name: tc_device_geofence; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_device_geofence" (
    "deviceid" integer NOT NULL,
    "geofenceid" integer NOT NULL
);


--
-- Name: tc_device_maintenance; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_device_maintenance" (
    "deviceid" integer NOT NULL,
    "maintenanceid" integer NOT NULL
);


--
-- Name: tc_device_notification; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_device_notification" (
    "deviceid" integer NOT NULL,
    "notificationid" integer NOT NULL
);


--
-- Name: tc_device_order; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_device_order" (
    "deviceid" integer NOT NULL,
    "orderid" integer NOT NULL
);


--
-- Name: tc_devices; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_devices" (
    "id" integer NOT NULL,
    "name" character varying(128) NOT NULL,
    "uniqueid" character varying(128) NOT NULL,
    "lastupdate" timestamp without time zone,
    "positionid" integer,
    "groupid" integer,
    "attributes" character varying(4000),
    "phone" character varying(128),
    "model" character varying(128),
    "contact" character varying(512),
    "category" character varying(128),
    "disabled" boolean DEFAULT false
);


--
-- Name: tc_devices_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_devices" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_devices_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_drivers; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_drivers" (
    "id" integer NOT NULL,
    "name" character varying(128) NOT NULL,
    "uniqueid" character varying(128) NOT NULL,
    "attributes" character varying(4000) NOT NULL
);


--
-- Name: tc_drivers_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_drivers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_drivers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_events; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_events" (
    "id" integer NOT NULL,
    "type" character varying(128) NOT NULL,
    "eventtime" timestamp without time zone NOT NULL,
    "deviceid" integer,
    "positionid" integer,
    "geofenceid" integer,
    "attributes" character varying(4000),
    "maintenanceid" integer
);


--
-- Name: tc_events_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_geofences; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_geofences" (
    "id" integer NOT NULL,
    "name" character varying(128) NOT NULL,
    "description" character varying(128),
    "area" character varying(4096) NOT NULL,
    "attributes" character varying(4000),
    "calendarid" integer
);


--
-- Name: tc_geofences_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_geofences" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_geofences_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_group_attribute; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_group_attribute" (
    "groupid" integer NOT NULL,
    "attributeid" integer NOT NULL
);


--
-- Name: tc_group_command; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_group_command" (
    "groupid" integer NOT NULL,
    "commandid" integer NOT NULL
);


--
-- Name: tc_group_driver; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_group_driver" (
    "groupid" integer NOT NULL,
    "driverid" integer NOT NULL
);


--
-- Name: tc_group_geofence; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_group_geofence" (
    "groupid" integer NOT NULL,
    "geofenceid" integer NOT NULL
);


--
-- Name: tc_group_maintenance; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_group_maintenance" (
    "groupid" integer NOT NULL,
    "maintenanceid" integer NOT NULL
);


--
-- Name: tc_group_notification; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_group_notification" (
    "groupid" integer NOT NULL,
    "notificationid" integer NOT NULL
);


--
-- Name: tc_group_order; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_group_order" (
    "groupid" integer NOT NULL,
    "orderid" integer NOT NULL
);


--
-- Name: tc_groups; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_groups" (
    "id" integer NOT NULL,
    "name" character varying(128) NOT NULL,
    "groupid" integer,
    "attributes" character varying(4000)
);


--
-- Name: tc_groups_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_maintenances; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_maintenances" (
    "id" integer NOT NULL,
    "name" character varying(4000) NOT NULL,
    "type" character varying(128) NOT NULL,
    "start" double precision DEFAULT 0 NOT NULL,
    "period" double precision DEFAULT 0 NOT NULL,
    "attributes" character varying(4000) NOT NULL
);


--
-- Name: tc_maintenances_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_maintenances" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_maintenances_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_notifications; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_notifications" (
    "id" integer NOT NULL,
    "type" character varying(128) NOT NULL,
    "attributes" character varying(4000),
    "always" boolean DEFAULT false NOT NULL,
    "calendarid" integer,
    "notificators" character varying(128)
);


--
-- Name: tc_notifications_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_notifications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_orders; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_orders" (
    "id" integer NOT NULL,
    "uniqueid" character varying(128) NOT NULL,
    "description" character varying(512),
    "fromAddress" character varying(512),
    "toAddress" character varying(512),
    "attributes" character varying(4000) NOT NULL
);


--
-- Name: tc_orders_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_orders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_orders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_positions; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_positions" (
    "id" integer NOT NULL,
    "protocol" character varying(128),
    "deviceid" integer NOT NULL,
    "servertime" timestamp without time zone DEFAULT "now"() NOT NULL,
    "devicetime" timestamp without time zone NOT NULL,
    "fixtime" timestamp without time zone NOT NULL,
    "valid" boolean NOT NULL,
    "latitude" double precision NOT NULL,
    "longitude" double precision NOT NULL,
    "altitude" double precision NOT NULL,
    "speed" double precision NOT NULL,
    "course" double precision NOT NULL,
    "address" character varying(512),
    "attributes" character varying(4000),
    "accuracy" double precision DEFAULT 0 NOT NULL,
    "network" character varying(4000)
);


--
-- Name: tc_positions_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_positions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_positions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_servers; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_servers" (
    "id" integer NOT NULL,
    "registration" boolean DEFAULT true NOT NULL,
    "latitude" double precision DEFAULT 0 NOT NULL,
    "longitude" double precision DEFAULT 0 NOT NULL,
    "zoom" integer DEFAULT 0 NOT NULL,
    "map" character varying(128),
    "bingkey" character varying(128),
    "mapurl" character varying(512),
    "readonly" boolean DEFAULT false NOT NULL,
    "twelvehourformat" boolean DEFAULT false NOT NULL,
    "attributes" character varying(4000),
    "forcesettings" boolean DEFAULT false NOT NULL,
    "coordinateformat" character varying(128),
    "devicereadonly" boolean DEFAULT false,
    "limitcommands" boolean DEFAULT false,
    "poilayer" character varying(512),
    "announcement" character varying(4000)
);


--
-- Name: tc_servers_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_servers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_servers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_statistics; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_statistics" (
    "id" integer NOT NULL,
    "capturetime" timestamp without time zone NOT NULL,
    "activeusers" integer DEFAULT 0 NOT NULL,
    "activedevices" integer DEFAULT 0 NOT NULL,
    "requests" integer DEFAULT 0 NOT NULL,
    "messagesreceived" integer DEFAULT 0 NOT NULL,
    "messagesstored" integer DEFAULT 0 NOT NULL,
    "attributes" character varying(4096) NOT NULL,
    "mailsent" integer DEFAULT 0 NOT NULL,
    "smssent" integer DEFAULT 0 NOT NULL,
    "geocoderrequests" integer DEFAULT 0 NOT NULL,
    "geolocationrequests" integer DEFAULT 0 NOT NULL,
    "protocols" character varying(4096)
);


--
-- Name: tc_statistics_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_statistics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_statistics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tc_user_attribute; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_attribute" (
    "userid" integer NOT NULL,
    "attributeid" integer NOT NULL
);


--
-- Name: tc_user_calendar; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_calendar" (
    "userid" integer NOT NULL,
    "calendarid" integer NOT NULL
);


--
-- Name: tc_user_command; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_command" (
    "userid" integer NOT NULL,
    "commandid" integer NOT NULL
);


--
-- Name: tc_user_device; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_device" (
    "userid" integer NOT NULL,
    "deviceid" integer NOT NULL
);


--
-- Name: tc_user_driver; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_driver" (
    "userid" integer NOT NULL,
    "driverid" integer NOT NULL
);


--
-- Name: tc_user_geofence; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_geofence" (
    "userid" integer NOT NULL,
    "geofenceid" integer NOT NULL
);


--
-- Name: tc_user_group; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_group" (
    "userid" integer NOT NULL,
    "groupid" integer NOT NULL
);


--
-- Name: tc_user_maintenance; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_maintenance" (
    "userid" integer NOT NULL,
    "maintenanceid" integer NOT NULL
);


--
-- Name: tc_user_notification; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_notification" (
    "userid" integer NOT NULL,
    "notificationid" integer NOT NULL
);


--
-- Name: tc_user_order; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_order" (
    "userid" integer NOT NULL,
    "orderid" integer NOT NULL
);


--
-- Name: tc_user_user; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_user_user" (
    "userid" integer NOT NULL,
    "manageduserid" integer NOT NULL
);


--
-- Name: tc_users; Type: TABLE; Schema: traccar; Owner: -
--

CREATE TABLE "traccar"."tc_users" (
    "id" integer NOT NULL,
    "name" character varying(128) NOT NULL,
    "email" character varying(128) NOT NULL,
    "hashedpassword" character varying(128),
    "salt" character varying(128),
    "readonly" boolean DEFAULT false NOT NULL,
    "administrator" boolean,
    "map" character varying(128),
    "latitude" double precision DEFAULT 0 NOT NULL,
    "longitude" double precision DEFAULT 0 NOT NULL,
    "zoom" integer DEFAULT 0 NOT NULL,
    "twelvehourformat" boolean DEFAULT false NOT NULL,
    "attributes" character varying(4000),
    "coordinateformat" character varying(128),
    "disabled" boolean DEFAULT false,
    "expirationtime" timestamp without time zone,
    "devicelimit" integer DEFAULT '-1'::integer,
    "token" character varying(128),
    "userlimit" integer DEFAULT 0,
    "devicereadonly" boolean DEFAULT false,
    "phone" character varying(128),
    "limitcommands" boolean DEFAULT false,
    "login" character varying(128),
    "poilayer" character varying(512)
);


--
-- Name: tc_users_id_seq; Type: SEQUENCE; Schema: traccar; Owner: -
--

ALTER TABLE "traccar"."tc_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "traccar"."tc_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."databasechangeloglock"
    ADD CONSTRAINT "databasechangeloglock_pkey" PRIMARY KEY ("id");


--
-- Name: tc_attributes tc_attributes_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_attributes"
    ADD CONSTRAINT "tc_attributes_pkey" PRIMARY KEY ("id");


--
-- Name: tc_calendars tc_calendars_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_calendars"
    ADD CONSTRAINT "tc_calendars_pkey" PRIMARY KEY ("id");


--
-- Name: tc_commands tc_commands_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_commands"
    ADD CONSTRAINT "tc_commands_pkey" PRIMARY KEY ("id");


--
-- Name: tc_devices tc_devices_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_devices"
    ADD CONSTRAINT "tc_devices_pkey" PRIMARY KEY ("id");


--
-- Name: tc_devices tc_devices_uniqueid_key; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_devices"
    ADD CONSTRAINT "tc_devices_uniqueid_key" UNIQUE ("uniqueid");


--
-- Name: tc_drivers tc_drivers_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_drivers"
    ADD CONSTRAINT "tc_drivers_pkey" PRIMARY KEY ("id");


--
-- Name: tc_drivers tc_drivers_uniqueid_key; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_drivers"
    ADD CONSTRAINT "tc_drivers_uniqueid_key" UNIQUE ("uniqueid");


--
-- Name: tc_events tc_events_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_events"
    ADD CONSTRAINT "tc_events_pkey" PRIMARY KEY ("id");


--
-- Name: tc_geofences tc_geofences_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_geofences"
    ADD CONSTRAINT "tc_geofences_pkey" PRIMARY KEY ("id");


--
-- Name: tc_groups tc_groups_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_groups"
    ADD CONSTRAINT "tc_groups_pkey" PRIMARY KEY ("id");


--
-- Name: tc_maintenances tc_maintenances_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_maintenances"
    ADD CONSTRAINT "tc_maintenances_pkey" PRIMARY KEY ("id");


--
-- Name: tc_notifications tc_notifications_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_notifications"
    ADD CONSTRAINT "tc_notifications_pkey" PRIMARY KEY ("id");


--
-- Name: tc_orders tc_orders_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_orders"
    ADD CONSTRAINT "tc_orders_pkey" PRIMARY KEY ("id");


--
-- Name: tc_positions tc_positions_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_positions"
    ADD CONSTRAINT "tc_positions_pkey" PRIMARY KEY ("id");


--
-- Name: tc_servers tc_servers_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_servers"
    ADD CONSTRAINT "tc_servers_pkey" PRIMARY KEY ("id");


--
-- Name: tc_statistics tc_statistics_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_statistics"
    ADD CONSTRAINT "tc_statistics_pkey" PRIMARY KEY ("id");


--
-- Name: tc_users tc_users_email_key; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_users"
    ADD CONSTRAINT "tc_users_email_key" UNIQUE ("email");


--
-- Name: tc_users tc_users_pkey; Type: CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_users"
    ADD CONSTRAINT "tc_users_pkey" PRIMARY KEY ("id");


--
-- Name: event_deviceid_servertime; Type: INDEX; Schema: traccar; Owner: -
--

CREATE INDEX "event_deviceid_servertime" ON "traccar"."tc_events" USING "btree" ("deviceid", "eventtime");


--
-- Name: position_deviceid_fixtime; Type: INDEX; Schema: traccar; Owner: -
--

CREATE INDEX "position_deviceid_fixtime" ON "traccar"."tc_positions" USING "btree" ("deviceid", "fixtime");


--
-- Name: user_device_user_id; Type: INDEX; Schema: traccar; Owner: -
--

CREATE INDEX "user_device_user_id" ON "traccar"."tc_user_device" USING "btree" ("userid");


--
-- Name: tc_device_command fk_device_command_commandid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_command"
    ADD CONSTRAINT "fk_device_command_commandid" FOREIGN KEY ("commandid") REFERENCES "traccar"."tc_commands"("id") ON DELETE CASCADE;


--
-- Name: tc_device_command fk_device_command_deviceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_command"
    ADD CONSTRAINT "fk_device_command_deviceid" FOREIGN KEY ("deviceid") REFERENCES "traccar"."tc_devices"("id") ON DELETE CASCADE;


--
-- Name: tc_device_driver fk_device_driver_deviceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_driver"
    ADD CONSTRAINT "fk_device_driver_deviceid" FOREIGN KEY ("deviceid") REFERENCES "traccar"."tc_devices"("id") ON DELETE CASCADE;


--
-- Name: tc_device_driver fk_device_driver_driverid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_driver"
    ADD CONSTRAINT "fk_device_driver_driverid" FOREIGN KEY ("driverid") REFERENCES "traccar"."tc_drivers"("id") ON DELETE CASCADE;


--
-- Name: tc_device_geofence fk_device_geofence_deviceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_geofence"
    ADD CONSTRAINT "fk_device_geofence_deviceid" FOREIGN KEY ("deviceid") REFERENCES "traccar"."tc_devices"("id") ON DELETE CASCADE;


--
-- Name: tc_device_geofence fk_device_geofence_geofenceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_geofence"
    ADD CONSTRAINT "fk_device_geofence_geofenceid" FOREIGN KEY ("geofenceid") REFERENCES "traccar"."tc_geofences"("id") ON DELETE CASCADE;


--
-- Name: tc_device_maintenance fk_device_maintenance_deviceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_maintenance"
    ADD CONSTRAINT "fk_device_maintenance_deviceid" FOREIGN KEY ("deviceid") REFERENCES "traccar"."tc_devices"("id") ON DELETE CASCADE;


--
-- Name: tc_device_maintenance fk_device_maintenance_maintenanceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_maintenance"
    ADD CONSTRAINT "fk_device_maintenance_maintenanceid" FOREIGN KEY ("maintenanceid") REFERENCES "traccar"."tc_maintenances"("id") ON DELETE CASCADE;


--
-- Name: tc_device_notification fk_device_notification_deviceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_notification"
    ADD CONSTRAINT "fk_device_notification_deviceid" FOREIGN KEY ("deviceid") REFERENCES "traccar"."tc_devices"("id") ON DELETE CASCADE;


--
-- Name: tc_device_notification fk_device_notification_notificationid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_notification"
    ADD CONSTRAINT "fk_device_notification_notificationid" FOREIGN KEY ("notificationid") REFERENCES "traccar"."tc_notifications"("id") ON DELETE CASCADE;


--
-- Name: tc_device_order fk_device_order_deviceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_order"
    ADD CONSTRAINT "fk_device_order_deviceid" FOREIGN KEY ("deviceid") REFERENCES "traccar"."tc_devices"("id") ON DELETE CASCADE;


--
-- Name: tc_device_order fk_device_order_orderid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_order"
    ADD CONSTRAINT "fk_device_order_orderid" FOREIGN KEY ("orderid") REFERENCES "traccar"."tc_orders"("id") ON DELETE CASCADE;


--
-- Name: tc_devices fk_devices_groupid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_devices"
    ADD CONSTRAINT "fk_devices_groupid" FOREIGN KEY ("groupid") REFERENCES "traccar"."tc_groups"("id") ON DELETE SET NULL;


--
-- Name: tc_events fk_events_deviceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_events"
    ADD CONSTRAINT "fk_events_deviceid" FOREIGN KEY ("deviceid") REFERENCES "traccar"."tc_devices"("id") ON DELETE CASCADE;


--
-- Name: tc_geofences fk_geofence_calendar_calendarid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_geofences"
    ADD CONSTRAINT "fk_geofence_calendar_calendarid" FOREIGN KEY ("calendarid") REFERENCES "traccar"."tc_calendars"("id") ON DELETE SET NULL;


--
-- Name: tc_group_attribute fk_group_attribute_attributeid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_attribute"
    ADD CONSTRAINT "fk_group_attribute_attributeid" FOREIGN KEY ("attributeid") REFERENCES "traccar"."tc_attributes"("id") ON DELETE CASCADE;


--
-- Name: tc_group_attribute fk_group_attribute_groupid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_attribute"
    ADD CONSTRAINT "fk_group_attribute_groupid" FOREIGN KEY ("groupid") REFERENCES "traccar"."tc_groups"("id") ON DELETE CASCADE;


--
-- Name: tc_group_command fk_group_command_commandid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_command"
    ADD CONSTRAINT "fk_group_command_commandid" FOREIGN KEY ("commandid") REFERENCES "traccar"."tc_commands"("id") ON DELETE CASCADE;


--
-- Name: tc_group_command fk_group_command_groupid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_command"
    ADD CONSTRAINT "fk_group_command_groupid" FOREIGN KEY ("groupid") REFERENCES "traccar"."tc_groups"("id") ON DELETE CASCADE;


--
-- Name: tc_group_driver fk_group_driver_driverid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_driver"
    ADD CONSTRAINT "fk_group_driver_driverid" FOREIGN KEY ("driverid") REFERENCES "traccar"."tc_drivers"("id") ON DELETE CASCADE;


--
-- Name: tc_group_driver fk_group_driver_groupid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_driver"
    ADD CONSTRAINT "fk_group_driver_groupid" FOREIGN KEY ("groupid") REFERENCES "traccar"."tc_groups"("id") ON DELETE CASCADE;


--
-- Name: tc_group_geofence fk_group_geofence_geofenceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_geofence"
    ADD CONSTRAINT "fk_group_geofence_geofenceid" FOREIGN KEY ("geofenceid") REFERENCES "traccar"."tc_geofences"("id") ON DELETE CASCADE;


--
-- Name: tc_group_geofence fk_group_geofence_groupid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_geofence"
    ADD CONSTRAINT "fk_group_geofence_groupid" FOREIGN KEY ("groupid") REFERENCES "traccar"."tc_groups"("id") ON DELETE CASCADE;


--
-- Name: tc_group_maintenance fk_group_maintenance_groupid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_maintenance"
    ADD CONSTRAINT "fk_group_maintenance_groupid" FOREIGN KEY ("groupid") REFERENCES "traccar"."tc_groups"("id") ON DELETE CASCADE;


--
-- Name: tc_group_maintenance fk_group_maintenance_maintenanceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_maintenance"
    ADD CONSTRAINT "fk_group_maintenance_maintenanceid" FOREIGN KEY ("maintenanceid") REFERENCES "traccar"."tc_maintenances"("id") ON DELETE CASCADE;


--
-- Name: tc_group_notification fk_group_notification_groupid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_notification"
    ADD CONSTRAINT "fk_group_notification_groupid" FOREIGN KEY ("groupid") REFERENCES "traccar"."tc_groups"("id") ON DELETE CASCADE;


--
-- Name: tc_group_notification fk_group_notification_notificationid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_notification"
    ADD CONSTRAINT "fk_group_notification_notificationid" FOREIGN KEY ("notificationid") REFERENCES "traccar"."tc_notifications"("id") ON DELETE CASCADE;


--
-- Name: tc_group_order fk_group_order_groupid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_order"
    ADD CONSTRAINT "fk_group_order_groupid" FOREIGN KEY ("groupid") REFERENCES "traccar"."tc_groups"("id") ON DELETE CASCADE;


--
-- Name: tc_group_order fk_group_order_orderid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_group_order"
    ADD CONSTRAINT "fk_group_order_orderid" FOREIGN KEY ("orderid") REFERENCES "traccar"."tc_orders"("id") ON DELETE CASCADE;


--
-- Name: tc_groups fk_groups_groupid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_groups"
    ADD CONSTRAINT "fk_groups_groupid" FOREIGN KEY ("groupid") REFERENCES "traccar"."tc_groups"("id") ON UPDATE RESTRICT ON DELETE SET NULL;


--
-- Name: tc_notifications fk_notification_calendar_calendarid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_notifications"
    ADD CONSTRAINT "fk_notification_calendar_calendarid" FOREIGN KEY ("calendarid") REFERENCES "traccar"."tc_calendars"("id") ON UPDATE RESTRICT ON DELETE SET NULL;


--
-- Name: tc_positions fk_positions_deviceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_positions"
    ADD CONSTRAINT "fk_positions_deviceid" FOREIGN KEY ("deviceid") REFERENCES "traccar"."tc_devices"("id") ON DELETE CASCADE;


--
-- Name: tc_user_attribute fk_user_attribute_attributeid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_attribute"
    ADD CONSTRAINT "fk_user_attribute_attributeid" FOREIGN KEY ("attributeid") REFERENCES "traccar"."tc_attributes"("id") ON DELETE CASCADE;


--
-- Name: tc_user_attribute fk_user_attribute_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_attribute"
    ADD CONSTRAINT "fk_user_attribute_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_user_calendar fk_user_calendar_calendarid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_calendar"
    ADD CONSTRAINT "fk_user_calendar_calendarid" FOREIGN KEY ("calendarid") REFERENCES "traccar"."tc_calendars"("id") ON DELETE CASCADE;


--
-- Name: tc_user_calendar fk_user_calendar_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_calendar"
    ADD CONSTRAINT "fk_user_calendar_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_user_command fk_user_command_commandid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_command"
    ADD CONSTRAINT "fk_user_command_commandid" FOREIGN KEY ("commandid") REFERENCES "traccar"."tc_commands"("id") ON DELETE CASCADE;


--
-- Name: tc_user_command fk_user_command_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_command"
    ADD CONSTRAINT "fk_user_command_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_device_attribute fk_user_device_attribute_attributeid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_attribute"
    ADD CONSTRAINT "fk_user_device_attribute_attributeid" FOREIGN KEY ("attributeid") REFERENCES "traccar"."tc_attributes"("id") ON DELETE CASCADE;


--
-- Name: tc_device_attribute fk_user_device_attribute_deviceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_device_attribute"
    ADD CONSTRAINT "fk_user_device_attribute_deviceid" FOREIGN KEY ("deviceid") REFERENCES "traccar"."tc_devices"("id") ON DELETE CASCADE;


--
-- Name: tc_user_device fk_user_device_deviceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_device"
    ADD CONSTRAINT "fk_user_device_deviceid" FOREIGN KEY ("deviceid") REFERENCES "traccar"."tc_devices"("id") ON DELETE CASCADE;


--
-- Name: tc_user_device fk_user_device_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_device"
    ADD CONSTRAINT "fk_user_device_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_user_driver fk_user_driver_driverid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_driver"
    ADD CONSTRAINT "fk_user_driver_driverid" FOREIGN KEY ("driverid") REFERENCES "traccar"."tc_drivers"("id") ON DELETE CASCADE;


--
-- Name: tc_user_driver fk_user_driver_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_driver"
    ADD CONSTRAINT "fk_user_driver_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_user_geofence fk_user_geofence_geofenceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_geofence"
    ADD CONSTRAINT "fk_user_geofence_geofenceid" FOREIGN KEY ("geofenceid") REFERENCES "traccar"."tc_geofences"("id") ON DELETE CASCADE;


--
-- Name: tc_user_geofence fk_user_geofence_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_geofence"
    ADD CONSTRAINT "fk_user_geofence_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_user_group fk_user_group_groupid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_group"
    ADD CONSTRAINT "fk_user_group_groupid" FOREIGN KEY ("groupid") REFERENCES "traccar"."tc_groups"("id") ON DELETE CASCADE;


--
-- Name: tc_user_group fk_user_group_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_group"
    ADD CONSTRAINT "fk_user_group_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_user_maintenance fk_user_maintenance_maintenanceid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_maintenance"
    ADD CONSTRAINT "fk_user_maintenance_maintenanceid" FOREIGN KEY ("maintenanceid") REFERENCES "traccar"."tc_maintenances"("id") ON DELETE CASCADE;


--
-- Name: tc_user_maintenance fk_user_maintenance_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_maintenance"
    ADD CONSTRAINT "fk_user_maintenance_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_user_notification fk_user_notification_notificationid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_notification"
    ADD CONSTRAINT "fk_user_notification_notificationid" FOREIGN KEY ("notificationid") REFERENCES "traccar"."tc_notifications"("id") ON DELETE CASCADE;


--
-- Name: tc_user_notification fk_user_notification_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_notification"
    ADD CONSTRAINT "fk_user_notification_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_user_order fk_user_order_orderid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_order"
    ADD CONSTRAINT "fk_user_order_orderid" FOREIGN KEY ("orderid") REFERENCES "traccar"."tc_orders"("id") ON DELETE CASCADE;


--
-- Name: tc_user_order fk_user_order_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_order"
    ADD CONSTRAINT "fk_user_order_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_user_user fk_user_user_manageduserid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_user"
    ADD CONSTRAINT "fk_user_user_manageduserid" FOREIGN KEY ("manageduserid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Name: tc_user_user fk_user_user_userid; Type: FK CONSTRAINT; Schema: traccar; Owner: -
--

ALTER TABLE ONLY "traccar"."tc_user_user"
    ADD CONSTRAINT "fk_user_user_userid" FOREIGN KEY ("userid") REFERENCES "traccar"."tc_users"("id") ON DELETE CASCADE;


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: traccar; Owner: -
--

INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.3', 'author', 'changelog-3.3', '2022-02-02 00:00:00.000000', 3, 'MARK_RAN', '8:ea6f202534dc7845fd1a49e1d8384d9c', 'createTable tableName=users; addUniqueConstraint constraintName=uk_user_email, tableName=users; createTable tableName=devices; addUniqueConstraint constraintName=uk_device_uniqueid, tableName=devices; createTable tableName=user_device; addForeignK...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.0-clean', 'author', 'changelog-4.0-clean', '2022-02-02 00:00:00.000000', 1, 'EXECUTED', '8:d59fa93049c031a8bcfbc02958c1942c', 'createTable tableName=tc_attributes; createTable tableName=tc_calendars; createTable tableName=tc_commands; createTable tableName=tc_device_attribute; createTable tableName=tc_device_command; createTable tableName=tc_device_driver; createTable tab...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.0-clean-common', 'author', 'changelog-4.0-clean', '2022-02-02 00:00:00.000000', 2, 'EXECUTED', '8:1adabae3238e02ccc97cc422359a58a0', 'addForeignKeyConstraint baseTableName=tc_groups, constraintName=fk_groups_groupid, referencedTableName=tc_groups; addForeignKeyConstraint baseTableName=tc_user_user, constraintName=fk_user_user_manageduserid, referencedTableName=tc_users', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.5', 'author', 'changelog-3.5', '2022-02-02 00:00:00.000000', 4, 'MARK_RAN', '8:194e3ae7ec6d201917136e04a26e237b', 'createTable tableName=groups; createTable tableName=user_group; addForeignKeyConstraint baseTableName=user_group, constraintName=fk_user_group_userid, referencedTableName=users; addForeignKeyConstraint baseTableName=user_group, constraintName=fk_u...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.6', 'author', 'changelog-3.6', '2022-02-02 00:00:00.000000', 5, 'MARK_RAN', '8:1ec7941b03749f24e365bc6126b07e1a', 'createTable tableName=events; addForeignKeyConstraint baseTableName=events, constraintName=fk_event_deviceid, referencedTableName=devices; addColumn tableName=devices; createTable tableName=geofences; createTable tableName=user_geofence; addForeig...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.7', 'author', 'changelog-3.7', '2022-02-02 00:00:00.000000', 6, 'MARK_RAN', '8:2e444e379f31d0b8e09273ec7ffe87a0', 'update tableName=devices; addForeignKeyConstraint baseTableName=devices, constraintName=fk_device_group_groupid, referencedTableName=groups; update tableName=groups; addColumn tableName=devices; dropColumn columnName=motion, tableName=devices; dro...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.7-notmssql', 'author', 'changelog-3.7', '2022-02-02 00:00:00.000000', 7, 'MARK_RAN', '8:974c33d2fb399ef6477c3897450fb078', 'addForeignKeyConstraint baseTableName=groups, constraintName=fk_group_group_groupid, referencedTableName=groups', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.8', 'author', 'changelog-3.8', '2022-02-02 00:00:00.000000', 8, 'MARK_RAN', '8:74d68027951f8d2ae6bb2e24df8365bc', 'createTable tableName=attribute_aliases; addForeignKeyConstraint baseTableName=attribute_aliases, constraintName=fk_attribute_aliases_deviceid, referencedTableName=devices; addUniqueConstraint constraintName=uk_deviceid_attribute, tableName=attrib...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.9', 'author', 'changelog-3.9', '2022-02-02 00:00:00.000000', 9, 'MARK_RAN', '8:34822842d65deb843a7d16f857d52ecc', 'addColumn tableName=notifications; update tableName=notifications; update tableName=notifications; update tableName=notifications; update tableName=notifications', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.10', 'author', 'changelog-3.10', '2022-02-02 00:00:00.000000', 10, 'MARK_RAN', '8:e1ddbe83e1ecf856a912755fc118f82e', 'createTable tableName=calendars; createTable tableName=user_calendar; addForeignKeyConstraint baseTableName=user_calendar, constraintName=fk_user_calendar_userid, referencedTableName=users; addForeignKeyConstraint baseTableName=user_calendar, cons...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.10-notmssql', 'author', 'changelog-3.10', '2022-02-02 00:00:00.000000', 11, 'MARK_RAN', '8:191c21d8f0f921845cf93bbc9d0639b9', 'addForeignKeyConstraint baseTableName=user_user, constraintName=fk_user_user_manageduserid, referencedTableName=users', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.10-mssql', 'author', 'changelog-3.10', '2022-02-02 00:00:00.000000', 12, 'MARK_RAN', '8:ad1f63566e8d08812fbf0b93a118ef6e', 'sql', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.7-mssql', 'author', 'changelog-3.10', '2022-02-02 00:00:00.000000', 13, 'MARK_RAN', '8:127b36b9d32a9d236df51d19b18c3766', 'sql', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.11', 'author', 'changelog-3.11', '2022-02-02 00:00:00.000000', 14, 'MARK_RAN', '8:7800f890b9706a480bd5a79b591b6ca7', 'addColumn tableName=users; addColumn tableName=notifications; addColumn tableName=server; addColumn tableName=server; addColumn tableName=users', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.12', 'author', 'changelog-3.12', '2022-02-02 00:00:00.000000', 15, 'MARK_RAN', '8:5ce520811d626ad325a014b9fcbb1a13', 'addColumn tableName=statistics; createTable tableName=attributes; createTable tableName=user_attribute; addForeignKeyConstraint baseTableName=user_attribute, constraintName=fk_user_attribute_userid, referencedTableName=users; addForeignKeyConstrai...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.12-notmssql', 'author', 'changelog-3.12', '2022-02-02 00:00:00.000000', 16, 'MARK_RAN', '8:a3bf7fabcde29e106fe2f89829a76a84', 'dropForeignKeyConstraint baseTableName=groups, constraintName=fk_group_group_groupid; addForeignKeyConstraint baseTableName=groups, constraintName=fk_groups_groupid, referencedTableName=groups', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.12-pgsql', 'author', 'changelog-3.12', '2022-02-02 00:00:00.000000', 17, 'MARK_RAN', '8:cfc881bd2dadb561aa9c1a467bc8cc1c', 'dropColumn columnName=data, tableName=calendars; addColumn tableName=calendars', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.14', 'author', 'changelog-3.14', '2022-02-02 00:00:00.000000', 18, 'MARK_RAN', '8:1be7e6c0520f8be53ef1b099d96afba5', 'createTable tableName=drivers; addUniqueConstraint constraintName=uk_driver_uniqueid, tableName=drivers; createTable tableName=user_driver; addForeignKeyConstraint baseTableName=user_driver, constraintName=fk_user_driver_userid, referencedTableNam...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.15', 'author', 'changelog-3.15', '2022-02-02 00:00:00.000000', 19, 'MARK_RAN', '8:ac8ccec176027e98bbf45dc6c15d9b05', 'dropForeignKeyConstraint baseTableName=attribute_aliases, constraintName=fk_attribute_aliases_deviceid; dropUniqueConstraint constraintName=uk_deviceid_attribute, tableName=attribute_aliases; dropTable tableName=attribute_aliases; dropColumn colum...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.16', 'author', 'changelog-3.16', '2022-02-02 00:00:00.000000', 20, 'MARK_RAN', '8:b59407d70bfe9bf57bc9968adfbbdf1c', 'addColumn tableName=devices; addColumn tableName=users; addColumn tableName=servers; addColumn tableName=notifications; addForeignKeyConstraint baseTableName=notifications, constraintName=fk_notification_calendar_calendarid, referencedTableName=ca...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.3-admin', 'author', 'changelog-3.17', '2022-02-02 00:00:00.000000', 21, 'MARK_RAN', '8:3f14c3b08068eb7628d0d3e2941eb2d3', 'renameColumn newColumnName=administrator, oldColumnName=admin, tableName=users', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-3.17', 'author', 'changelog-3.17', '2022-02-02 00:00:00.000000', 22, 'MARK_RAN', '8:8aa3e56afe6ba86cd004fa801507bc28', 'addColumn tableName=events; createTable tableName=maintenances; createTable tableName=user_maintenance; addForeignKeyConstraint baseTableName=user_maintenance, constraintName=fk_user_maintenance_userid, referencedTableName=users; addForeignKeyCons...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.0-pre', 'author', 'changelog-4.0', '2022-02-02 00:00:00.000000', 23, 'MARK_RAN', '8:3974bfe5a2e962c0cd663433c832c16a', 'addColumn tableName=notifications', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.0-common', 'author', 'changelog-4.0', '2022-02-02 00:00:00.000000', 24, 'MARK_RAN', '8:65fb49c5be37693183708351c507dd50', 'update tableName=notifications; update tableName=notifications; update tableName=notifications; update tableName=notifications; update tableName=notifications; update tableName=notifications; update tableName=notifications', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.0-pg', 'author', 'changelog-4.0', '2022-02-02 00:00:00.000000', 25, 'MARK_RAN', '8:9831511507d8ae1d6759c8ccf506a27a', 'update tableName=notifications; update tableName=notifications; update tableName=notifications; update tableName=notifications; update tableName=notifications; update tableName=notifications; update tableName=notifications', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.0', 'author', 'changelog-4.0', '2022-02-02 00:00:00.000000', 26, 'MARK_RAN', '8:ac63c4153f5b2ee5c7a07056da269571', 'dropDefaultValue columnName=web, tableName=notifications; dropColumn columnName=web, tableName=notifications; dropDefaultValue columnName=mail, tableName=notifications; dropColumn columnName=mail, tableName=notifications; dropDefaultValue columnNa...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.0-renaming', 'author', 'changelog-4.0', '2022-02-02 00:00:00.000000', 27, 'MARK_RAN', '8:90aedfa378aa717f8d8ae541f97b87b2', 'renameTable newTableName=tc_attributes, oldTableName=attributes; renameTable newTableName=tc_calendars, oldTableName=calendars; renameTable newTableName=tc_commands, oldTableName=commands; renameTable newTableName=tc_device_attribute, oldTableName...', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.1-mssql', 'author', 'changelog-4.1', '2022-02-02 00:00:00.000000', 28, 'MARK_RAN', '8:b148f52efe9c6a3e74a56e33e257a3e2', 'sql; sql; sql; sql', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.7', 'author', 'changelog-4.7', '2022-02-02 00:00:00.000000', 29, 'EXECUTED', '8:a23040cfc84d4b8021f40ee214a9d78b', 'createIndex indexName=user_device_user_id, tableName=tc_user_device; createIndex indexName=position_deviceid_fixtime, tableName=tc_positions', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.9', 'author', 'changelog-4.9', '2022-02-02 00:00:00.000000', 30, 'EXECUTED', '8:805ef202791dcc246373ca16f7c19c4f', 'createIndex indexName=event_deviceid_servertime, tableName=tc_events', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.10', 'author', 'changelog-4.10', '2022-02-02 00:00:00.000000', 31, 'EXECUTED', '8:64f89f4092585f8f768d0dee54dc30c8', 'addColumn tableName=tc_statistics', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.11', 'author', 'changelog-4.11', '2022-02-02 00:00:00.000000', 32, 'EXECUTED', '8:234eaa970d9202e9a90b6534050f59ab', 'addColumn tableName=tc_servers', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.13', 'author', 'changelog-4.13', '2022-02-02 00:00:00.000000', 33, 'EXECUTED', '8:015570907a13a62d5eb01cea87ccebd8', 'renameColumn newColumnName=eventtime, oldColumnName=servertime, tableName=tc_events', '', NULL, '4.7.0', NULL, NULL, '3861135508');
INSERT INTO "traccar"."databasechangelog" VALUES ('changelog-4.15', 'author', 'changelog-4.15', '2022-02-02 00:00:00.000000', 34, 'EXECUTED', '8:247904615a0ae53ec78fed0243951bde', 'createTable tableName=tc_orders; createTable tableName=tc_user_order; addForeignKeyConstraint baseTableName=tc_user_order, constraintName=fk_user_order_userid, referencedTableName=tc_users; addForeignKeyConstraint baseTableName=tc_user_order, cons...', '', NULL, '4.7.0', NULL, NULL, '3861135508');


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: traccar; Owner: -
--

INSERT INTO "traccar"."databasechangeloglock" VALUES (1, false, NULL, NULL);


--
-- Data for Name: tc_servers; Type: TABLE DATA; Schema: traccar; Owner: -
--

INSERT INTO "traccar"."tc_servers" VALUES (1, true, 24, 78, 4, NULL, NULL, NULL, false, false, NULL, false, NULL, false, false, NULL, NULL);


--
-- Data for Name: tc_users; Type: TABLE DATA; Schema: traccar; Owner: -
--

INSERT INTO "traccar"."tc_users" VALUES (1, 'admin', 'admin', 'D33DCA55ABD4CC5BC76F2BC0B4E603FE2C6F61F4C1EF2D47', '000000000000000000000000000000000000000000000000', false, true, NULL, 0, 0, 0, false, NULL, NULL, false, NULL, -1, NULL, 0, false, NULL, false, NULL, NULL);


-- 

SELECT "create_hypertable"('traccar.tc_positions', 'id', chunk_time_interval => 100000);

--
-- PostgreSQL database dump complete
--

